---
- name: Install and launch Metricbeat
  hosts: webservers
  become: true
  tasks:

  - name: Download Metricbeat deb
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb

  - name: Install Metricbeat
    command: dpkg -i metricbeat-7.6.1-amd64.deb

  - name: Drop in metricbeat.yml
    copy:
      src: /etc/ansible/files/metricbeat_config.yml
      dest: /etc/metricbeat/metricbeat.yml

  - name: Enable and configure system module
    command: metricbeat modules enable docker

  - name: Setup Metricbeat
    command: metricbeat setup

  - name: Start Metricbeat
    command: service metricbeat start
